apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: katerndahl
  name: ceph-output
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30G
