apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: katerndahl
  name: ceph-input
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200G
