apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: katerndahl
  name: workdir-geoflow
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 120G
