apiVersion: v1
kind: Pod
metadata:
  namespace: katerndahl
  name: ceph-pod-geoflow
spec:
  containers:
  - name: ceph
    image: ubuntu
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /workdir
        name: workdir
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ceph-volume-geoflow
  - name: workdir
    persistentVolumeClaim:
      claimName: workdir-volume