apiVersion: v1
kind: Pod
metadata:
  name: geoflow-pod
  labels:
    'purpose': 'debug'
spec:
  containers:
  - name: geoflow
    image: floriankaterndahl/geoflow
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    volumeMounts:
      - mountPath: /data
        name: data
    securityContext:
      runAsUser: 0
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ceph-volume-geoflow
