# from https://docs.docker.com/ci-cd/github-actions/

name: CI to Docker Hub
on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull old image
        run: docker pull floriankaterndahl/geoflow:latest

      - name: Build image
        run: docker build . --file Dockerfile --tag floriankaterndahl/geoflow:latest
        
      - name: Push image
        run: docker push floriankaterndahl/geoflow:latest
        
