# from https://docs.docker.com/ci-cd/github-actions/

name: CI to Docker Hub
on:
  push:
    paths:
      - '.github/workflows/push_docker.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - 'python-script/*'
      - 'external/custom-requirements.txt'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/Dockerfile
          #builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/geoflow:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
